name: Get available action data

on:
  push:
    branches:
      - main

  schedule:
    - cron: 7 0 * * 1-5

  # run manually
  workflow_dispatch:

jobs:
  get-action-data:
    runs-on: ubuntu-latest

    steps:
    - uses: test-gha-market/load-available-actions@v1.2.12
      name: Load available actions
      id: load-actions
      with:
        PAT: ${{ secrets.PAT_GITHUB }}
        user: ${{ github.repository_owner }}

    # todo: convert this part into an action to make it more transferable. Don't forget to update the readme then!
    - run: npm install fs
    - uses: actions/github-script@v6
      with:
        script: |
          let actions = '${{ steps.load-actions.outputs.actions }}';
          const fs = require("fs");
          const fileName = 'actions-data.json';
          fs.writeFileSync(fileName, actions, function(err) {
            if(err) {
              return console.log("error")
            }
          })

    - name: Upload result file as artefact
      uses: actions/upload-artifact@v3
      with:
        name: actions
        path: actions-data.json

    - name: Upload json to this repository
      #uses: LasyIsLazy/github-upload-action@v0.1.0
      uses: test-gha-market/github-upload-action@v0.2.0
      with:
        access-token: ${{ secrets.PAT_GITHUB }}
        file-path: actions-data.json
        owner: ${{ github.repository_owner }}
        repo: actions-marketplace # ${{ github.repository }} doesn't work with this action :-(, it'll fail over the slash and owner name
        #remote-dir:  // upload in the root
        branch-name: gh-pages
