on: 
  push:
    branches:
      - main

  schedule:
    - cron: 7 0 * * 1-5

  # run manually
  workflow_dispatch:

jobs:
  get-action-data:
    runs-on: ubuntu-latest

    steps:
    - uses: devops-actions/load-available-actions@v1.2.12
      name: Load available actions
      id: load-actions
      with: 
        PAT: ${{ secrets.PAT }}
        user: ${{ github.repository_owner }}

    - shell: bash
      name: Store json file
      run: |
        echo '${{ steps.load-actions.outputs.actions }}' > 'actions-data.json'
          
    - name: Upload result file as artefact
      uses: actions/upload-artifact@v2
      with: 
        name: actions
        path: actions-data.json
   
    - name: Upload json to this repository
      #uses: LasyIsLazy/github-upload-action@v0.1.0
      uses: rajbos-actions/github-upload-action@v0.2.0
      with:
        access-token: ${{ secrets.PAT }}
        file-path: actions-data.json
        owner: ${{ github.repository_owner }}
        repo: actions-marketplace # ${{ github.repository }} doesn't work with this action :-(, it'll fail over the slash and owner name
        #remote-dir:  // upload in the root
        branch-name: gh-pages
